import express from "express";
import type { Request, Response } from "express";

let capturedApp:any=null; let serverLoadPromise:Promise<void>|null=null;
async function ensureExpressServerLoaded(){if(capturedApp)return;if(!serverLoadPromise)serverLoadPromise=(async()=>{const originalListen=(express.application as any).listen;try{(express.application as any).listen=function(..._args:any[]){capturedApp=this;return{on(){return this;},close(cb?:()=>void){cb?.();}} as any};process.env.NODE_ENV="production";await import("../server.ts");}finally{(express.application as any).listen=originalListen;}})();await serverLoadPromise;}
function norm(v:any){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"");}
function first(text:string,patterns:RegExp[]){for(const p of patterns){const m=text.match(p);if(m?.[1])return m[1].trim();}return null;}
function money(v:any){if(v==null||String(v).trim()==="-")return 0;const n=Number(String(v).replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:0;}
function pdfGlobals(){const g:any=globalThis;if(typeof g.DOMMatrix==="undefined")g.DOMMatrix=class{constructor(_x?:any){} multiply(){return this} preMultiplySelf(){return this} translate(){return this} scale(){return this} rotate(){return this} inverse(){return this}};if(typeof g.ImageData==="undefined")g.ImageData=class{data:any;width:number;height:number;constructor(a:any,b:any,c?:any){if(typeof a==="number"){this.width=a;this.height=b;this.data=new Uint8ClampedArray(a*b*4)}else{this.data=a;this.width=b;this.height=c||0}}};if(typeof g.Path2D==="undefined")g.Path2D=class{constructor(_x?:any){} addPath(){} moveTo(){} lineTo(){} rect(){} closePath(){} bezierCurveTo(){} quadraticCurveTo(){} arc(){} arcTo(){} ellipse(){}};}
async function extractPdfText(dataUrl:string){pdfGlobals();const b64=dataUrl.includes(",")?dataUrl.split(",")[1]:dataUrl;const buffer=Buffer.from(b64,"base64");const worker:any=await import("pdf-parse/worker");const mod:any=await import("pdf-parse");if(mod.PDFParse){if(typeof mod.PDFParse.setWorker==="function"){const workerPath=typeof worker.getPath==="function"?worker.getPath():typeof worker.getData==="function"?worker.getData():null;if(workerPath)mod.PDFParse.setWorker(workerPath);}const parser=new mod.PDFParse({data:buffer,CanvasFactory:worker.CanvasFactory});try{const out:any=await parser.getText();return typeof out==="string"?out:String(out?.text||"")}finally{await parser.destroy?.()}}if(typeof mod.default==="function"){const out:any=await mod.default(buffer);return String(out?.text||"")}throw new Error("Local PDF text engine unavailable");}
function accountChunks(text:string){const before=(text.split(/ENQUIRY DETAILS/i)[0]||text);let chunks=before.split(/(?=Member Name\s*[:\n])/i).slice(1);if(!chunks.length)chunks=before.split(/\bMember Name\b/i).slice(1);return chunks;}
function normalizeStatus(raw:string|null,overdue:number,written:number,settlement:number,closed:string|null){const s=String(raw||"");if(/written[\s-]*off/i.test(s)||written>0)return "Written-Off";if(/settled/i.test(s)||settlement>0)return "Settled";if(overdue>0)return "Overdue";if(closed&&closed!=="-")return "Closed";return "Active";}
function parseDpdHistory(c:string){const out:any[]=[];for(const m of c.matchAll(/(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[\s-]+(20\d{2})[\s:]+(\d{1,4}|XXX|STD|SMA|SUB|DBT|LSS|SET)\b/gi)){let dpd=String(m[3]).toUpperCase();if(/^\d+$/.test(dpd)){const n=Number(dpd);dpd=n===0?"000":n<=30?"030":n<=60?"060":n<=90?"090":"120+";}out.push({month:m[1],year:m[2],dpd});}return out;}
function parseAccounts(text:string){return accountChunks(text).map((c,i)=>{const institution=first(c,[/Member Name\s*:?\s*([^\n\r]+)/i,/^\s*([^\n\r]+)/])||"Credit Institution";const accountType=first(c,[/Account Type\s*:?\s*([^\n\r]+)/i])||"Credit Account";const accountNumber=first(c,[/Account Number\s*:?\s*([^\n\r]+)/i])||`ACCOUNT-${i+1}`;const sanctionedAmount=money(first(c,[/Sanctioned Amount\s*:?\s*₹?\s*([\d,.-]+)/i,/High Credit\s*:?\s*₹?\s*([\d,.-]+)/i]));const currentBalance=money(first(c,[/Current Balance\s*:?\s*₹?\s*([\d,.-]+)/i]));const overdueAmount=money(first(c,[/Amount Overdue\s*:?\s*₹?\s*([\d,.-]+)/i]));const rawStatus=first(c,[/Credit Facility Status\s*:?\s*([^\n\r]+)/i,/Account Status\s*:?\s*([^\n\r]+)/i]);const written=money(first(c,[/Written[- ]off Amount \(Total\)\s*:?\s*₹?\s*([\d,.-]+)/i]));const settlement=money(first(c,[/Settlement Amount\s*:?\s*₹?\s*([\d,.-]+)/i]));const openedDate=first(c,[/Date Opened\s*\/\s*Disbursed\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4})/i])||"-";const closedDate=first(c,[/Date Closed\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4}|-)/i]);const lastReportedDate=first(c,[/Date Reported And Certified\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4})/i])||"-";const dpdHistory=parseDpdHistory(c);return{id:`cibil-${i+1}`,institution,accountType,accountNumberMasked:accountNumber,sanctionedAmount,currentBalance,overdueAmount,status:normalizeStatus(rawStatus,overdueAmount,written,settlement,closedDate),openedDate,closedDate:closedDate&&closedDate!=="-"?closedDate:undefined,lastReportedDate,dpdHistory};}).filter(a=>a.accountType||a.accountNumberMasked);}
function parseEnquiries(text:string){const p=text.split(/ENQUIRY DETAILS/i)[1]||"";let chunks=p.split(/(?=Member Name\s*[:\n])/i).slice(1);if(!chunks.length)chunks=p.split(/\bMember Name\b/i).slice(1);return chunks.map(c=>({lender:first(c,[/Member Name\s*:?\s*([^\n\r]+)/i,/^\s*([^\n\r]+)/])||"Credit Institution",date:first(c,[/Date Of Enquiry\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4})/i])||"-",purpose:first(c,[/Enquiry Purpose\s*:?\s*([^\n\r]+)/i])||"Credit Enquiry",amount:money(first(c,[/Enquiry Amount\s*:?\s*₹?\s*([\d,.-]+)/i]))})).filter(e=>e.date!=="-"||e.lender!=="Credit Institution");}
function scoreBand(score:number){return score<650?"Poor":score<700?"Fair":score<750?"Good":"Excellent";}
function parseLocal(text:string,customerName?:string,panNumber?:string,dob?:string,fileName?:string,fileDataUrl?:string){const scoreRaw=first(text,[/Your CIBIL Score is\s*([3-9]\d{2})/i,/CIBIL Score[^\d]{0,40}([3-9]\d{2})\b/i]);const score=scoreRaw?Number(scoreRaw):0;const controlNumber=first(text,[/Control Number\s*:?\s*([\d,]+)/i])||"-";const reportDate=first(text,[/Your CIBIL Score is\s*[3-9]\d{2}\s+as of Date\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4})/i,/Date\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4})/i])||"-";const pan=first(text,[/Income Tax ID Number \(PAN\)[\s\S]{0,160}?([A-Z]{5}\d{4}[A-Z])/i,/\b([A-Z]{5}\d{4}[A-Z])\b/])||"";const foundDob=first(text,[/Date Of Birth\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4})/i])||"";const name=first(text,[/Hello,\s*([^\n\r.]+)/i,/PERSONAL DETAILS[\s\S]{0,160}?Name\s*:?\s*([^\n\r]+)/i])||"";const accounts=parseAccounts(text);const enquiries=parseEnquiries(text);const open=accounts.filter(a=>a.status!=="Closed");const written=accounts.filter(a=>a.status==="Written-Off");const settled=accounts.filter(a=>a.status==="Settled");const totalOverdue=accounts.reduce((s,a)=>s+a.overdueAmount,0);const totalOutstanding=open.reduce((s,a)=>s+Math.max(a.currentBalance,0),0);const cards=open.filter(a=>/credit card/i.test(a.accountType)).length;const loans=Math.max(0,open.length-cards);const dpdInstances=accounts.reduce((s,a)=>s+a.dpdHistory.filter((d:any)=>d.dpd!=="000"&&d.dpd!=="XXX").length,0);const matched=[Boolean(customerName&&name&&norm(customerName)===norm(name)),Boolean(panNumber&&pan&&norm(panNumber)===norm(pan)),Boolean(dob&&foundDob&&String(dob).replace(/\D/g,"")===String(foundDob).replace(/\D/g,""))];return{bureauName:"TransUnion CIBIL",score,scoreBand:scoreBand(score),reportDate,controlNumber,uploadedFileName:fileName,rawFileDataUrl:fileDataUrl,originalReportSource:"FILE_UPLOAD",verifiedProfile:{matchedName:name,matchedDob:foundDob,matchedPan:pan,isNameVerified:matched[0],isDobVerified:matched[2],isPanVerified:matched[1],verificationScore:Math.round(matched.filter(Boolean).length/3*100),verificationNotes:"Identity fields compared only with values extracted from uploaded bureau report."},summary:{activeLoansCount:loans,activeCreditCardsCount:cards,totalOutstanding,totalOverdue,settledAccountsCount:settled.length,writtenOffAccountsCount:written.length,totalEnquiries:enquiries.length,creditUtilizationPercent:0,dpdInstances},accounts,enquiries};}
async function handleCibil(req:Request,res:Response){try{const{fileName,fileDataUrl,customerName,panNumber,dob}=req.body||{};if(!fileDataUrl)return res.status(400).json({success:false,message:"Please upload a CIBIL PDF before analysis."});const text=await extractPdfText(String(fileDataUrl));if(!text.trim())return res.status(422).json({success:false,message:"PDF contains no extractable text."});const report=parseLocal(text,customerName,panNumber,dob,fileName,fileDataUrl);if(!report.score||!report.accounts.length)return res.status(422).json({success:false,message:"CIBIL PDF was read but score/account structure could not be verified. Please use an original text-based CIBIL PDF."});return res.json({success:true,message:"CIBIL report analyzed locally without paid AI credits.",report});}catch(error:any){console.error("Local CIBIL analyzer error",error);return res.status(500).json({success:false,message:error?.message||"Failed to analyze CIBIL report locally"});}}
export default async function handler(req:Request,res:Response){const path=req.url?.split("?")[0]||"";if(req.method==="GET"&&path==="/api/health")return res.json({status:"ok",app:"Savrdh Credit Resolution Customer App",runtime:"vercel-serverless",cibilAnalyzer:"local-normalized-v2"});if(req.method==="POST"&&path==="/api/cibil/parse-report")return handleCibil(req,res);try{await ensureExpressServerLoaded();}catch(error:any){return res.status(500).json({success:false,message:"Backend initialization failed",error:error?.message});}if(!capturedApp)return res.status(503).json({success:false,message:"SAVRDH API is initializing. Please retry."});return capturedApp(req,res);}
