import express from "express";
import type { Request, Response } from "express";

let capturedApp:any=null; let serverLoadPromise:Promise<void>|null=null;
async function ensureExpressServerLoaded(){if(capturedApp)return;if(!serverLoadPromise)serverLoadPromise=(async()=>{const originalListen=(express.application as any).listen;try{(express.application as any).listen=function(..._args:any[]){capturedApp=this;return{on(){return this;},close(cb?:()=>void){cb?.();}} as any};process.env.NODE_ENV="production";await import("../server.ts");}finally{(express.application as any).listen=originalListen;}})();await serverLoadPromise;}
function norm(v:any){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"");}
function responseText(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const item of data?.output||[])for(const c of item?.content||[])if(typeof c?.text==="string")return c.text;return "";}

const CIBIL_SCHEMA={type:"object",additionalProperties:false,required:["bureauName","score","controlNumber","reportDate","customerDetails","summary","accounts","enquiries","warnings"],properties:{
 bureauName:{type:["string","null"]},score:{type:["integer","null"]},controlNumber:{type:["string","null"]},reportDate:{type:["string","null"]},
 customerDetails:{type:"object",additionalProperties:false,required:["name","pan","dob"],properties:{name:{type:["string","null"]},pan:{type:["string","null"]},dob:{type:["string","null"]}}},
 summary:{type:"object",additionalProperties:false,required:["activeLoansCount","activeCreditCardsCount","totalOutstanding","totalOverdue","settledAccountsCount","writtenOffAccountsCount","totalEnquiries","creditUtilizationPercent","dpdInstances"],properties:{activeLoansCount:{type:"integer"},activeCreditCardsCount:{type:"integer"},totalOutstanding:{type:"number"},totalOverdue:{type:"number"},settledAccountsCount:{type:"integer"},writtenOffAccountsCount:{type:"integer"},totalEnquiries:{type:"integer"},creditUtilizationPercent:{type:["number","null"]},dpdInstances:{type:"integer"}}},
 accounts:{type:"array",items:{type:"object",additionalProperties:false,required:["id","memberName","accountType","accountNumber","ownership","sanctionedAmount","currentBalance","overdueAmount","status","writtenOffAmountTotal","settlementAmount","dateOpened","dateClosed","dateReported","emiAmount","maxDpd","isOpen"],properties:{id:{type:"integer"},memberName:{type:["string","null"]},accountType:{type:["string","null"]},accountNumber:{type:["string","null"]},ownership:{type:["string","null"]},sanctionedAmount:{type:["number","null"]},currentBalance:{type:["number","null"]},overdueAmount:{type:["number","null"]},status:{type:["string","null"]},writtenOffAmountTotal:{type:["number","null"]},settlementAmount:{type:["number","null"]},dateOpened:{type:["string","null"]},dateClosed:{type:["string","null"]},dateReported:{type:["string","null"]},emiAmount:{type:["number","null"]},maxDpd:{type:["integer","null"]},isOpen:{type:"boolean"}}}},
 enquiries:{type:"array",items:{type:"object",additionalProperties:false,required:["memberName","dateOfEnquiry","enquiryPurpose","amount"],properties:{memberName:{type:["string","null"]},dateOfEnquiry:{type:["string","null"]},enquiryPurpose:{type:["string","null"]},amount:{type:["number","null"]}}}},warnings:{type:"array",items:{type:"string"}}
}};

async function analyzeCibilWithOpenAI(fileDataUrl:string,fileName:string){
 const key=process.env.OPENAI_API_KEY;if(!key)throw Object.assign(new Error("OpenAI CIBIL analyzer is not configured. Add OPENAI_API_KEY in Vercel Production Environment Variables."),{code:"OPENAI_NOT_CONFIGURED"});
 const prompt=`You are a credit-bureau document extraction engine for SAVRDH Financial Services. Analyze ONLY the attached Indian credit report PDF. Extract facts exactly as printed. Never invent, estimate, infer a missing amount, or reuse example/demo data. Missing values must be null or zero only where the schema requires a numeric aggregate. Distinguish open and closed accounts. Preserve Written-off and Settled status exactly. Calculate summary totals only from extracted accounts. DPD means days past due; maxDpd is the maximum numeric DPD visibly reported for that account. For masked account numbers preserve the visible masked form. The result will be validated before being shown to a customer.`;
 const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_CIBIL_MODEL||"gpt-5-mini",input:[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_file",filename:fileName||"cibil-report.pdf",file_data:fileDataUrl}]}],text:{format:{type:"json_schema",name:"cibil_report",strict:true,schema:CIBIL_SCHEMA}}})});
 const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||`OpenAI analyzer failed (${r.status})`);const text=responseText(data);if(!text)throw new Error("OpenAI analyzer returned no structured report");return JSON.parse(text);
}

function validateReport(report:any,customerName?:string,panNumber?:string,dob?:string){
 const errors:string[]=[];if(report.score!==null&&(report.score<300||report.score>900))errors.push("CIBIL score is outside 300-900 range");if(report.customerDetails?.pan&&!/^[A-Z]{5}\d{4}[A-Z]$/i.test(report.customerDetails.pan))errors.push("Extracted PAN format is invalid");
 const sum=(report.accounts||[]).reduce((s:number,a:any)=>s+(Number(a.overdueAmount)||0),0);if(Math.abs(sum-(Number(report.summary?.totalOverdue)||0))>1)errors.push("Total overdue does not match account-level overdue values");
 const written=(report.accounts||[]).filter((a:any)=>/written[\s-]*off/i.test(a.status||"")||(Number(a.writtenOffAmountTotal)||0)>0).length;if(written!==Number(report.summary?.writtenOffAccountsCount||0))errors.push("Written-off account count does not match extracted accounts");
 return {errors,verifiedProfile:{matchedName:report.customerDetails?.name||null,matchedPan:report.customerDetails?.pan||null,matchedDob:report.customerDetails?.dob||null,isPanVerified:Boolean(panNumber&&report.customerDetails?.pan&&norm(panNumber)===norm(report.customerDetails.pan)),isNameVerified:Boolean(customerName&&report.customerDetails?.name&&norm(customerName)===norm(report.customerDetails.name)),isDobVerified:Boolean(dob&&report.customerDetails?.dob&&String(dob).replace(/\D/g,"")===String(report.customerDetails.dob).replace(/\D/g,""))}};
}

async function handleCibil(req:Request,res:Response){try{const {fileName,fileDataUrl,customerName,panNumber,dob}=req.body||{};if(!fileDataUrl)return res.status(400).json({success:false,message:"Please upload a CIBIL PDF before analysis."});if(!String(fileName||"").toLowerCase().endsWith(".pdf")&&!String(fileDataUrl).startsWith("data:application/pdf"))return res.status(415).json({success:false,message:"Only PDF credit reports are supported."});const report=await analyzeCibilWithOpenAI(String(fileDataUrl),String(fileName||"cibil-report.pdf"));const validation=validateReport(report,customerName,panNumber,dob);if(validation.errors.length)return res.status(422).json({success:false,code:"CIBIL_VALIDATION_FAILED",message:"CIBIL report was extracted but failed consistency validation.",validationErrors:validation.errors});report.verifiedProfile=validation.verifiedProfile;report.extractionMeta={mode:"OPENAI_DOCUMENT_INTELLIGENCE",model:process.env.OPENAI_CIBIL_MODEL||"gpt-5-mini",validated:true,warnings:report.warnings||[]};return res.json({success:true,message:"CIBIL report analyzed and validated.",report});}catch(error:any){console.error("OpenAI CIBIL analyzer error",error);return res.status(error?.code==="OPENAI_NOT_CONFIGURED"?503:500).json({success:false,code:error?.code||"CIBIL_AI_ANALYSIS_FAILED",message:error?.message||"Failed to analyze CIBIL report"});}}

export default async function handler(req:Request,res:Response){const path=req.url?.split("?")[0]||"";if(req.method==="GET"&&path==="/api/health")return res.json({status:"ok",app:"Savrdh Credit Resolution Customer App",runtime:"vercel-serverless",cibilAnalyzer:process.env.OPENAI_API_KEY?"openai-ready":"openai-key-missing"});if(req.method==="POST"&&path==="/api/cibil/parse-report")return handleCibil(req,res);try{await ensureExpressServerLoaded();}catch(error:any){return res.status(500).json({success:false,message:"Backend initialization failed",error:error?.message});}if(!capturedApp)return res.status(503).json({success:false,message:"SAVRDH API is initializing. Please retry."});return capturedApp(req,res);}
